### PR TITLE
python scripts for multiple scenarios

### PR DESCRIPTION
**Pull request by BakytzhanSuleimenov**
Tool extension for handling multiple scenarios at ones
python scripts to split multiple scenario export from veda 
python script to generate json files for those multiple scenarios

### CODE REVIEW

**Comment by olejandro** [comment]
Bakha, so basically what you are doing in this PR, is you are moving the original code from the jupyter notebook to a `*.py` file to be run as a script, correct? I.e. I was surprised to see a lot of code added that looked like mine, until I realised what was going on. 😄

**Review by olejandro — COMMENTED** [review]
The original intention for this tool was to be run as a jupyter notebook. This PR is changing that original purpose / introduces code duplication. I don't think I am the right person to approve that kind of a change in this repository, but maybe @energynumbers is? I have my own fork which is maintained with the original purpose in mind.

**Comment by BakytzhanSuleimenov** [comment]
Hi Olex,

Mostly this is right that I have turned the notebook to the script, however, I have also added one more "for" loop on top to do the task for all folders within the given path. 
Additionally, I have added the "utils" folder with a Python script to split CSV files with multiple scenario outputs (batch task from Veda for many scenarios) to folders with results for each scenario. 

Also, I am adding a .bat files, so one who is going to use it just needs to put his Veda CSV output files to the given folder, then run two .bat files, so he is set to start a result repository directly after this.

Maybe, we can put everything in utils folder. 

Thanks for feedback

**Comment by olejandro** [comment]
>I have also added one more "for" loop on top to do the task for all folders within the given path. Additionally, I have added the "utils" folder with a Python script to split CSV files with multiple scenario outputs (batch task from Veda for many scenarios) to folders with results for each scenario.

Thanks, Bakha. I am bit confused why you needed to do this. The results are split into scenario specific subfolders already, i.e.: 
```
with open(output_folder / aScenario / (aTable + ".json"), "w", encoding="utf-8") as file:
            js_str = json.dumps(data_dict, indent=2)
            file.write(js_str)
```
If the purpose of the changes is to run the code as a script, e.g. by calling it in a bat file, you could probably use this: https://nbconvert.readthedocs.io/en/latest/execute_api.html#executing-notebooks-from-the-command-line

**Comment by BakytzhanSuleimenov** [comment]
This part is as it is, I have added only for input folder. So input folder contains many scenario subfolders and it will run for all result subfolders. This was main reason. Vahid is running multiple scenarios, I was thinking to prepare many scenarios at once to be exported to the netlify app.

**Comment by olejandro** [comment]
I see... Why does the input folder contain many scenario subfolders? When using batch export to csv, Veda normally generates a single file per table with multiple scenarios in it.

**Comment by BakytzhanSuleimenov** [comment]
Aah, this is the functionality already, I was thinking that this handles one scenario output per export. Then I can discard this PR. 
Sorry for the confusion

**Comment by olejandro** [comment]
At some point @ankitagaur93 was writing a manual to describe how the system functions. Depending on how far she got, maybe one could update the README to make the fuctionality clearer?

**Pull request closed without merging**
